voxpupuli/voxpupuli-test

lib/voxpupuli/test/spec_helper.rb

This code comes from modulesync_config:
https://github.com/voxpupuli/modulesync_config/commit/666105af193d036d8f150676f8c4704d2abd5e30

Determine correct facter version based on puppet

---

lib/voxpupuli/test/spec_helper.rb

Collection of facts can be slow. By memoizing subsequent calls are sped up greatly.
In puppet-nginx test collection was reduced from 1 minute 52 seconds down to 15 seconds. That has 9 calls to on_supported_os.

Memoize rspec-puppet-facts

---

lib/voxpupuli/test/rake.rb

By defining the default task, there is no separate Travis configuration needed and it works out of the box.

Define a default task

---

voxpupuli-test.gemspec

This contains facts for Debian 10 which is a common platform to test.

Require at least facterdb 1.3.0 for Debian 10

---

voxpupuli-test.gemspec

This provides us Ubuntu 20.04 factset for Facter 3.14.

depend on facterdb 1.4.0

---

voxpupuli-test.gemspec

I tested this for my own modules, also the foreman people use it:
https://github.com/theforeman/foreman-installer-modulesync/blob/8e29149d17efd144371d5c46baff9f04fbb79141/config_defaults.yml#L5-L11

Add puppet-lint-file_ensure-check

---

voxpupuli-test.gemspec

This will keep this gem compatible with the pdk gem
See https://github.com/voxpupuli/pdksync_config/issues/1#issuecomment-612988064

Update rubocop-rspec dependency

---

rubocop.yml

When this is enabled, trailing comma's for elements in a hash are not allowed. This is not the style that Puppet uses and causes code churn. This change would disable that functionality.

Disable Style/TrailingCommaInLiteral

---

voxpupuli-test.gemspec

This reverts commit 692fa31ad9ba3091b348908c0e03d4acd9f84d7a.
A new version of rspec-puppet has been released, and this pin should no
longer be necessary (and may have been causing some other issues of its
own).

Revert "Pin `rspec-expectations`"

---

rubocop.yml

Currently the trailing , in
```ruby
it {
is_expected.to contain_concat__fragment('nftables-inet-filter-chain-default_out-rule-dnsudp').with(
target:  'nftables-inet-filter-chain-default_out',
content: %r{^  udp dport 53 accept$},
order:   '50-nftables-inet-filter-chain-default_out-rule-dnsudp-b',
)
}
```
throws a warning. This is inconsistent with what is permitted in
puppet.

Disable Style/TrailingCommaInArguments

---

voxpupuli-test.gemspec

Hi,
@alexjfisher I checked out your linter plugin and it seems to work fine. I also found some params that indeed assign data to an undef var so I think it's a useful addition to our linting and works fine.

add puppet-lint-optional_default-check

---

lib/voxpupuli/test/spec_helper.rb
voxpupuli-test.gemspec

This already happens in rspec-puppet-facts itself and there's no reason to duplicate it. There it's also more correct by taking all variables into account.
Draft because it depends on https://github.com/mcanevet/rspec-puppet-facts/pull/122 being merged and released as 2.1.0.

Remove fact memoization

---

voxpupuli-test.gemspec

puppet-lint is required for Ruby 3 support.

Depend on puppet-lint >= 2.5.0

---

README.md
lib/voxpupuli/test/rake.rb
voxpupuli-test.gemspec

I tested this successfully on the bird module:
```
bastelfreak@bastelfreak-nb ~/code/modulesync_config/modules/voxpupuli/puppet-bird $ git diff
diff --git a/Gemfile b/Gemfile
index 930d8da..57e246a 100644
--- a/Gemfile
+++ b/Gemfile
@@ -4,10 +4,12 @@
source ENV['GEM_SOURCE'] || "https://rubygems.org"
group :test do
-  gem 'voxpupuli-test', '~> 2.1',  :require => false
+  #gem 'voxpupuli-test', '~> 2.1',  :require => false
+  gem 'voxpupuli-test', git: 'https://github.com/bastelfreak/voxpupuli-test.git', branch: 'msp'
gem 'coveralls',                 :require => false
gem 'simplecov-console',         :require => false
gem 'puppet-lint-param-docs',    :require => false
+  #gem 'metadata_json_deps', git: 'https://github.com/bastelfreak/metadata_json_deps', branch: '3'
end
group :development …
```

Add metadata_json_deps + rake task

---

lib/voxpupuli/test/spec_helper.rb

Since rspec-puppet-facts 2.0.0 the default Facter version is derived from the Puppet version. There is no more need to do this locally. It also handles Puppet 7 which our code doesn't.
I should note I didn't test this yet.

Use default facter version from rspec-puppet-facts

---

voxpupuli-test.gemspec

This ensures we get at least metadata-json-lint 3 and not the way older 3.

require metadata-json-lint 3 or newer/metadata_json_deps 0.3.0 or newer

---

voxpupuli-test.gemspec

install meta gem to pull in all puppet-lint plugins + puppet-lint itself. Tested at https://github.com/voxpupuli/puppet-borg/pull/121

Use voxpupuli-puppet-lint-plugins

---

voxpupuli-test.gemspec

This will pull in puppet-lint-top_scope_facts-check. We did prio checks
and fixed the violations in all common used modules we have.

Require voxpupuli-puppet-lint-plugins 2.x

---

lib/voxpupuli/test/rake.rb

I am pretty sure that in the past we failed on puppet-lint already. with
our latest setup we continue in the CI pipeline even if puppet-lint
detects issues. This might be caused by the recent
puppetlabs_spec_helper update.

puppet-lint: fail on warnings

---

lib/voxpupuli/test/spec_helper.rb
voxpupuli-test.gemspec

This completely disables Facter and uses a stubbed implementation. This is fine since we use use rspec-puppet-facts to set all facts. It gives complete isolation from the host system and is also significantly faster with Facter 4 (which always also resolves the facts, see [FACT-3039]).  It only works with Puppet 6.25+ and 7.12+ and requires rspec-puppet 2.11.0+.
FACT-3039: https://tickets.puppetlabs.com/browse/FACT-3039

Set facter implementation to rspec

---

rubocop.yml

In the Puppet world, symbols are often used instead of proper booleans
in type properties, (which don't work with actual booleans).
Since we probably have more false positives than real cases we should
disable this cop.

Disable `Lint/BooleanSymbol`

---

rubocop.yml

Enabling this cop causes a lot of noise in our project, because ruboop
would want us to reformat most of the tests.
Explanation of the cop:
https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/ImplicitSubject

Rubocop: Disable ImplicitSubject

---

rubocop.yml

Example:
```ruby
def insync?(is)
```
That `is` parameter is all over the place in our modules.

rubocop: Naming/MethodParameterName: Add common short parameters names to AllowedNames

---

rubocop.yml

Example [here](https://github.com/voxpupuli/puppet-mongodb/blob/master/lib/puppet/functions/mongodb_password.rb#L12)
Changing this to `sensitive: false` causes spec to fail with `ArgumentError:  wrong number of arguments (given 3, expected 2)`
I've seen this failing in other modules as well. Possibly related to #66

rubocop: Disable Style/OptionalBooleanParameter

---

rubocop.yml

In the latest modulesync rubocop was auto-correcting:
```ruby
{
"foo"    => "bar",
"forbar" => "bar"
}
```
to 
```ruby
{
"foo" => "bar",
"forbar" => "bar"
}
```
Generally in the puppet world we are used to align to the => and a lot of specs are written this way (and I think it's better to stay this way)

Layout/HashAlignment: Allow both key and table styles

---

lib/voxpupuli/test/facts.rb
spec/facts_spec.rb

Since rspec-puppet-facts 1.9.5 (and in particular https://github.com/mcanevet/rspec-puppet-facts/commit/21b679f45b9e20902af53161b5e1bd0b4fb723f7) custom facts are stored as strings. Since this gem requires rspec-puppet-facts >= 2.0.1 they should be treated as such.
This also highlighted that we're incompatible with `RSpec.configuration.facterdb_string_keys` set to true, but most testing code in Vox Pupuli is incompatible with this.
Tests are added to ensure it really works and prevents future regressions.
It also changes the `service_provider` custom fact to use the operatingsystemmajrelease fact. This makes testing easier and it's consistent with the code for SuSE.

Correct systemd custom fact implementation

---

.github/workflows/test.yml
Gemfile

This now uses a similar setup as puppet-syntax. Sideeffect is that for Puppet 6 tests, we pull in the 6.29 version or newer, which has a fix to pin to concurrent-ruby 1.1 and older.

Enhance CI with more Ruby/Puppet versions

---

Gemfile
voxpupuli-test.gemspec

with the release of puppetlabs_spec_helper 5, it can validate the REFERENCE.md. It won't pull in puppet-strings automatically, so the dependency needs to be added. The `strings:validate:reference` task is called within `validate`.

require PSH 5.x, require puppet-strings

---

lib/voxpupuli/test/facts.rb
spec/facts_spec.rb

At some point soon, either facterdb will stop providing legacy facts or rspec-puppet-facts will be configurable to filter them out.  Either way, we should not rely on them in this gem and use the modern counterparts instead.

Remove use of legacy facts

---

.github/workflows/test.yml

This will prevent pulling in the broken 7.21 release or earlier, where ruby-concurrent in 1.2 is allowed, which is incompatible with Puppet.

CI: for Puppet 7, use 7.24 or newer

---

.github/workflows/test.yml
voxpupuli-test.gemspec

I would like to start add Puppet 8 support. To do this properly, we need to bump a few gems and that means we need to drop Ruby 2.5 and 2.6 support.

Require Ruby 2.7 or newer, drop Puppet 6 support

---

voxpupuli-test.gemspec

This ensures that we don't pull in unexpected major versions.

gem dependencies: Add upper version limits

---

lib/voxpupuli/test/spec_helper.rb

Foreman does that in their modules and I think it makes sense to always enable it.

always mock trusted/server facts

---

Gemfile
rubocop.yml

For the 8.0 we had to pin to 7.x because of a rubygems bug.

Gemfile: Allow Puppet 8

---

lib/voxpupuli/test/spec_helper.rb

The setting got removed in rspec-puppet 4:
https://github.com/puppetlabs/rspec-puppet/pull/73

dont set trusted_node_data/trusted_server_facts

---

voxpupuli-test.gemspec

latest version manages rspec like we need that. That means by requiering 7.3, we can delete .rspec/.rspec_parallel from modulesync_config.
https://github.com/voxpupuli/modulesync_config/pull/895

puppetlabs_spec_helper: Require 7.3

---

spec/facts_spec.rb
spec/spec_helper.rb

Previously our tests didn't honour our spec/spec_helper.rb. This configures some rspec defaults for our Puppet modules. It makes sense that our tests use the same settings. This revealed some problems in other PRs: https://github.com/voxpupuli/voxpupuli-test/pull/125

Use our spec_helper for tests

---

lib/voxpupuli/test/facts.rb
lib/voxpupuli/test/spec_helper.rb
spec/facts_spec.rb
voxpupuli-test.gemspec

This basically drops factsets for facter 1, 2 and 3. So it drops support for Puppet 6 and older. However, we don't support those anymore in our modules, so this isn't a breaking change.
The newer FacterDB release also drop support for some operating systems that were EoL as well.

rspec-puppet-facts: Require 4.x; add custom facts as strings 

---

Rakefile
lib/voxpupuli/test/facts.rb

Also adds a comment to a supressed exception. Both make RuboCop a little bit less unhappy.

Merge duplicate branches in service_provider fact

---

lib/voxpupuli/test/spec_helper.rb

Since `puppetlabs_spec_helper` 5.0.0 this is the default (https://github.com/puppetlabs/puppetlabs_spec_helper/commit/493f0cbc1c96a3fa67591f3936430a70af74847f) and our gemspec declares 7.3+ as the version, making this redundant.

Remove redundant mock_with default to rspec

---

lib/voxpupuli/test/rake.rb

feat(check:trailing_whitespace):  collect all problems, report and then exit

---

README.md

Document the trailing_whitespace rake task in the README

---

voxpupuli-test.gemspec

rspec-puppet-facts uses FacterDB 3, which removed legacy facts.

require rspec-puppet-facts 5.x; drop legacy facts support

---

README.md

This got extracted from https://github.com/voxpupuli/.github/pull/1

README.md: Document how to use voxpupuli-test

---

voxpupuli-test.gemspec

This release fixes the annoying warnings we saw a lot:
```
Could not retrieve fact ipaddress...
``

rspec-puppet: Require 5.x

---

voxpupuli-test.gemspec

PSH 8 drops some build tasks, that we don't use:
https://github.com/puppetlabs/puppetlabs_spec_helper/compare/v7.4.0...v8.0.0

puppetlabs_spec_helper: Require 8.x

---

voxpupuli-test.gemspec

puppet gem depends on syslog, but doesn't list it as explicit dependency until Ruby 3.4, syslog was part of MRI ruby core
Add it here as workaround until we've an openvox gem to depend on
Without this, we get warnings like:
```
.../.vendor/ruby/3.3.0/gems/puppet-8.10.0/lib/puppet.rb:38: warning: syslog was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.4.0.
```

Add syslog gem as dependency

---

voxpupuli-test.gemspec

I think we don't use this dependency and it's not maintained anymore. This is also required to get rid of puppetlabs_spec_helper.

Drop rspec-puppet-utils

---

lib/voxpupuli/test/rake/validate.rb

The validate:ruby rake task uses the `sh` method. That's provided by rake (???)
```
[1] pry(main)> show-method sh
Error: Couldn't locate a definition for sh
[2] pry(main)> require 'rake'
=> true
[3] pry(main)> show-method sh
From: /home/bastelfreak/code/voxpupuli-test/.vendor/ruby/3.4.0/gems/rake-13.2.1/lib/rake/file_utils.rb:15:
Owner: Rake::DSL
Visibility: private
Signature: sh(*cmd, &block)
Number of lines: 17
def sh(*cmd, &block)
options = (Hash === cmd.last) ? cmd.pop : {}
shell_runner = block_given? ? block : create_shell_runner(cmd)
set_verbose_option(options)
verbose = options.delete :verbose
noop    = options.delete(:noop) || Rake::FileUtilsExt.nowrite_flag
Rake.rake_output_message sh_show_command cmd if verbose
unless noop
res = (Hash === cmd.last) ? system(*cmd) : system(*cmd, …
```

validate rake task: Add missing rake dependency

---

lib/voxpupuli/test/rake/validate.rb

It's common that Bolt tasks are written in Ruby. Since we already validate Ruby files in modules, we can also validate the tasks. Tested:
```console
puppet-aptly $ bundle exec irb
irb(main):001> require 'rake'
=> true
irb(main):002*     Dir['lib/**/*.rb', 'tasks/**/*.rb'].each do |lib_file|
irb(main):003*       sh 'ruby', '-c', lib_file
irb(main):004>     end ;
ruby -c lib/cli_helper.rb
Syntax OK
ruby -c tasks/mirror_create.rb
Syntax OK
ruby -c tasks/mirror_drop.rb
Syntax OK
ruby -c tasks/mirror_list.rb
Syntax OK
ruby -c tasks/mirror_update.rb
Syntax OK
ruby -c tasks/publish_drop.rb
Syntax OK
ruby -c tasks/publish_list.rb
Syntax OK
ruby -c tasks/publish_repo.rb
Syntax OK
ruby -c tasks/publish_snapshot.rb
Syntax OK
ruby -c tasks/publish_switch.rb
Syntax OK
ruby -c tasks/publish_update.rb …
```

validate:ruby: Validate Ruby tasks

---

voxpupuli-test.gemspec

https://github.com/voxpupuli/voxpupuli-puppet-lint-plugins/releases/tag/6.0.0

voxpupuli-puppet-lint-plugins: require 6.x

---

.github/dependabot.yml

I noticed that dependabot wasn't running for some time. Maybe because of the spacing within the file. Thew new version is copied from the beaker repo, where dependabot works.

dependabot: fix configuration

---

voxpupuli-test.gemspec

The 6 release brings in some changes (most important is FacterDB 4 support):
**Breaking changes:**
- Require Ruby 3.2 or newer [\#224](https://github.com/voxpupuli/rspec-puppet-facts/pull/224) ([bastelfreak](https://github.com/bastelfreak))
- CI: Dont validate puppet\_agent\_facter\_versions.json anymore [\#223](https://github.com/voxpupuli/rspec-puppet-facts/pull/223) ([bastelfreak](https://github.com/bastelfreak))
- Switch from facter to openfact [\#219](https://github.com/voxpupuli/rspec-puppet-facts/pull/219) ([bastelfreak](https://github.com/bastelfreak))
**Implemented enhancements:**
- puppet\_agent\_facter\_versions: Add OpenVox/OpenFact versions [\#228](https://github.com/voxpupuli/rspec-puppet-facts/pull/228) ([bastelfreak](https://github.com/bastelfreak))
- FacterDB: Allow 4.x …

rspec-puppet-facts: Allow 6.x
